version: 0.2

phases:
  install:
    commands:
      - curl -o /usr/local/bin/jq -L https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x /usr/local/bin/jq
      # NOTE: ruby 1.9が落ちてくるが、標準ライブラリしか使用していないのでとりあえずそのまま
      - apt-get update && apt-get -y install ruby
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - touch dummy
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dummy
